projectName: NexisNex
type: program
language: cpp

includes: on

include:
  compiler:     "config/Nexis/Compiler.yaml"
  logger:       "config/Nexis/Logger.yaml"
  dependencies: "config/Nexis/Dependencies.yaml"